[project]
name = 'contrarcts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.traits]
path = 'contracts/traits.clar'
clarity_version = 3
epoch = '3.2'

[contracts.mock-usdcx]
path = 'contracts/mock-usdcx.clar'
clarity_version = 3
epoch = '3.2'

[contracts.tesla-stock]
path = 'contracts/tesla-stock.clar'
clarity_version = 3
epoch = '3.2'

[contracts.collateral-vault]
path = 'contracts/collateral-vault.clar'
clarity_version = 3
epoch = '3.2'

[contracts.dia-oracle-wrapper]
path = 'contracts/dia-oracle-wrapper.clar'
clarity_version = 3
epoch = '3.2'

[contracts.funding-settler]
path = 'contracts/funding-settler.clar'
clarity_version = 3
epoch = '3.2'

[contracts.liquidation-engine]
path = 'contracts/liquidation-engine.clar'
clarity_version = 3
epoch = 'latest'

[contracts.perp-engine]
path = 'contracts/perp-engine.clar'
clarity_version = 3
epoch = 'latest'


[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
